### ISSUE TITLE
update pykern version

### ISSUE THREAD

**Issue by cchall** [radiasoft/jupyter.radiasoft.org#115]
Update beamsim and beamsim-jupyter to use latest pykern version

**Comment by robnagler** [comment]
ran into a bug that doesn't allow you to get the new image https://github.com/radiasoft/container-jupyterhub/issues/5

**Comment by robnagler** [comment]
This is on beta. Please test. You will need to restart your server.

**Comment by cchall** [comment]
Everything on beta looks good.

Is the beamsim still to be updated? It looks like beamsim:beta was updated at the same time (sha256: fb9bcb144fee) but I still see an older version of pykern:
```
>>> pykern.__version__
'20200824.233924'
```

**Comment by robnagler** [comment]
Thanks for checking it out. 

Yes beamsim is older, but that image is not used directly.

On Cori, you should use radiasoft/sirepo:prod, which contains beamsim and the latest pykern. 

For rsmpi, we use radiasoft/beamsim-jupyter:prod, which is the same image running prod Jupyter. I've been updating rsmpi nodes on demand, because the nodes are often busy. When I do a prod release, I can do yours. Just LMK.

**Comment by cchall** [comment]
The reason I checked beamsim directly is that I use it as the base image for my Python interpreter in Pycharm. At the time it seemed like the way to go as the "lightest" of our available images, but maybe I should be using sirepo instead?

**Comment by robnagler** [comment]
sirepo has been trimmed recently so it's "only" 350MB (7%) heavier than beamsim. It is prod is now released weekly on Mondays so it's probably best to use. It always includes the most recent pykern at build time (the week before).
