### ISSUE TITLE
enable nbextension automatically

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/jupyter.radiasoft.org#12]
Certain javascript GUIs in IPython notebooks are failing in our Jupyter notebooks.

![image](https://user-images.githubusercontent.com/3825435/30179793-e0a98c2e-93ca-11e7-9476-c76deddc4bca.png)

At some time in the past, this wasn't a problem.

It may be that the following line is helpful and should be used when the server is restarted:
jupyter nbextension enable --py --sys-prefix widgetsnbextension

**Comment by robnagler** [comment]
Restart your server to get this fix. @ncook882

**Comment by robnagler** [comment]
I got it working in a container on my laptop using Jupyter 5.x. I don't think it is a big risk going to 5.x. Let me know if anybody cares. @ncook882 @cchall @sdwebb @bruhwiler 

It's complicated because we are running Jupyter with JupyterLab (necessary for CBCOM proxy thing), which required the latest JupyterHub, which requires the latest Jupyter, which of course only runs on Python 3. The kernel is running Python 2. The extensions have to be installed in both pyenv's afaict. And, I think Jupyter is serving the JSON from Python 3 that it needs to run the same version in both py2 and jupyter pyenv's.

**Comment by bruhwiler** [comment]
That does sound crazy complicated.
I trust your judgement -- let's move to Jupyter 5.x if you think it's the right thing to do.
Supporting these widgets is very important to some of our users.

**Comment by robnagler** [comment]
This is working now for me on jupyter.radiasoft. However, there's a new error in the CTH_test notebook related to self.avail_circ_modes being None, but that may be due to my diag directory or something else being messed up. A simple widget test works fine:

```python
import ipywidgets
ipywidgets.Text('Hello')
```

**Comment by bruhwiler** [comment]
Sounds good.  I see the same error that you describe, regarding self.avail_circ_modes being None.
That's probably a bug in the notebook.

Let's keep this issue open until we can fix the problem in our NB and verify that the plotting widget is working.

**Comment by robnagler** [comment]
Assume this is fixed.
