### ISSUE TITLE
Problem with vagrant password

### ISSUE THREAD

**Issue by Amirari** [radiasoft/jupyter.radiasoft.org#121]
Hi, I am trying to install a Geant4 wrapper called GAMOS on the JupyterLab through the terminal, when I do it requests the vagrant password. I have tried using my GithHub password and it works to log into JupyterLab but not to install packages. I have tried resetting my github password a couple times and that has not worked. I was wondering if there was additional permission I need to request through radiasoft or how I can go about installing GAMOS.

**Comment by robnagler** [comment]
@Amirari I spent time trying to compile GAMOS today. There are some issues, but none that you describe. I think there's a bug in the way the scripts work, but I was able to get quite far with:

```sh
curl -L http://fismed.ciemat.es/GAMOS/download/GAMOS.6.2.0/download_scripts.sh|bash
cd scripts
./installGamos.sh ~/jupyter/gamos
```

One of the modules (DCMTK) is not properly installed:

```sh
-- Installing: ../dcmtk-3.6.4-install.shared/usr/local/include/dcmtk/dcmpmap/dpmparametricmapiod.h
mv: cannot stat '../dcmtk-3.6.4-install.shared/usr/local/lib/': No such file or directory
cp: -r not specified; omitting directory '../dcmtk-3.6.4-install.shared/usr/local/lib64/cmake'
@@@ DCMTK IS CORRECTLY INSTALLED
mkdir: cannot create directory ‘/home/vagrant/jupyter/gamos’: File exists
CMAKE_VER 3 ZZ 14 ZZ 5
mkdir: cannot create directory ‘/home/vagrant/jupyter/gamos’: File exists
@@@@@@ Installing GAMOS at /home/vagrant/jupyter/gamos
curl found, downloading sources ...
```

The compile continues and eventually fails, because something is not installed:

```txt
/home/vagrant/jupyter/gamos/GAMOS.6.2.0/source/GamosCore/GamosBase/Base/include/GmAnalysisMgr.hh:5:10: fatal error: TH1F.h: No such file or directory
 #include "TH1F.h"
```

I could probably build this separately and install in Jupyter. 

@sjcrs I believe you might have built Geant4/GAMOS, correct?

**Comment by sjcrs** [comment]
I have built Geant4 but not the GAMOS wrapper. I recognize that TH1F.h is a ROOT library. Is there a ROOT dependency for the GAMOS build?

**Comment by Amirari** [comment]
Thank you @robnagler. I am not sure if this would help but there is a script that installs missing packages, I believe Jupyter runs on Fedora, and under scripts there is one for Fedora, installMissingPackages.Fedora.31.sh. The password request happens when I try to bash install the missing packages.

**Comment by sjcrs** [comment]
Ah, is this an issue with `make install` if a `--prefix` hasn't been specified for a user without sudo privileges?

**Comment by Amirari** [comment]
GAMOS does have a root dependency, I had to install missing packages on Ubuntu18.4 OS to get it to work on my work PC.

**Comment by robnagler** [comment]
installMissingPackages.Fedora.31.sh contains:

```txt
echo Fedora.31 > missingPackagesInstalled
sudo dnf install -y gcc-c++
sudo dnf install -y make-devel
sudo dnf install -y expat-devel
sudo dnf install -y libX11-devel
sudo dnf install -y libXpm-devel
sudo dnf install -y libXft-devel
sudo dnf install -y libXext-devel
sudo dnf install -y libXmu-devel
sudo dnf install -y libXi-devel
sudo dnf install -y libtiff-devel
sudo dnf install -y freeglut-devel
sudo dnf install -y glibc-devel
sudo dnf install -y zlib-devel
sudo dnf install -y pcre-devel
sudo dnf install -y cmake
sudo dnf install -y python-devel
sudo dnf install -y python-numpy
```

The program doesn't check if the packages are already installed, which most of them are. The `libX*` packages do not need to be installed, because X11 visualization does not work in Jupyter. I don't know if GAMOS will fail as a result, but it might. freeglut is an OpenGL library, which also won't work in Jupyter.

I think therefore you'll be fine if you do not install the missing packages.

As noted, the build fails for other reasons afaict. If you just want Geant4, here's how @sjcrs built it on Jupyter:

```sh
#Download Xerces for GDML support
export THISDIR=$PWD
wget https://ftp.wayne.edu/apache//xerces/c/3/sources/xerces-c-3.2.3.tar.gz
tar -zxvf xerces-c-3.2.3.tar.gz
cd xerces-c-3.2.3
mkdir build
cd build
../configure --prefix=$THISDIR/xerces-c-3.2.3/build/.
make -j5
make install
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$THISDIR/xerces-c-3.2.3/build/lib
#Get DAWN for visualization
cd $THISDIR
wget http://geant4.kek.jp/~tanaka/src/dawn_3_91a.tgz
tar -zxvf dawn_3_91a.tgz
#cd $THISDIR
rm -rf build
mkdir build
cd build
cmake ../ -DGEANT4_BUILD_MULTITHREADED=ON -DGEANT4_USE_GDML=ON -DXERCESC_ROOT_DIR=$THISDIR/xerces-c-3.2.3/build/
make -j5
```

**Comment by Amirari** [comment]
Hi, thank you for trying, I'll reach out to the GAMOS admins and see if they have any script updates for installing it to Jupyter, other wise I'll follow @sjrcs and just try to continue with Geant4 directly. Thanks again for all the help, I will keep you posted on what I hear back from the GAMOS admin
