### ISSUE TITLE
`Error 429: Too Many Requests` when accessing Jupyter

### ISSUE THREAD

**Issue by ncook882** [radiasoft/jupyter.radiasoft.org#29]
This error was reported by one of our users. I haven't been able to reproduce, but wanted to document here.

**Comment by robnagler** [comment]
Fix 1b94e31ca232d383f59a40e5b25ffad0ab695848

See https://github.com/radiasoft/jupyter.radiasoft.org#too-many-requests-429 for documentation.

**Comment by bruhwiler** [comment]
Is it possible to make the error message more informative?
Also, is it possible to log how often this is happening?

**Comment by robnagler** [comment]
> Is it possible to make the error message more informative?

Unfortunately, not. The server (rsdockerspawner) [tries to return an error](https://github.com/radiasoft/rsdockerspawner/blob/9fb308bddc255216aaa896b753b8d98dd2df670e/rsdockerspawner/rsdockerspawner.py#L464), but JupyterLab/Hub doesn't render it. If you refresh, it sometimes shows it.

> Also, is it possible to log how often this is happening?

There is a log. Someone would need to aggregate that particular statistic.

Turns out there was a bug in the garbage collector: https://github.com/radiasoft/rsdockerspawner/issues/5

**Comment by robnagler** [comment]
The garbage collector fix was pushed to prod.
