### ISSUE TITLE
Missing packages for the installation of Zgoubidoo

### ISSUE THREAD

**Issue by chernals** [radiasoft/jupyter.radiasoft.org#46]
Zgoubidoo requires packages that are not installed at the moment.

One of them is `parse`.

The full list can be found in the requirements.txt file or environment.yml file in the zgoubidoo repository.

**Comment by robnagler** [comment]
@chernals The instructions for installing zgoubidoo do not include installing `requirements.txt`. You should probably put all requirements on `install_requires` in `setup.py`.

I don't think `pip install -r requirements.txt` will work well the way `requirements.txt` is currently written, because the `install_requires` contains more specific entries. For zgoubidoo, you shouldn't need a `requirements.txt`. See [install_requires vs requirements files](https://packaging.python.org/discussions/install-requires-vs-requirements/) and its base reference [setup.py vs requirements.txt](https://caremad.io/posts/2013/07/setup-vs-requirement/).

I'll be rebuilding radiasoft/beamsim-jupyter later this week. In the mean time, you can call `pip3 install parse` once when your container starts.
